version: '3.9'
services:

  postgres:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    container_name: beauty-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - beauty:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  beauty: